### ISSUE TITLE
transition 过程

### ISSUE THREAD

**Issue by forzeny** [forzeny/Music-Player#2]
通过DOM -> break on -> attribute -> modification 观测class变化过程

![image](https://user-images.githubusercontent.com/18499153/34902660-3aab99fc-f85b-11e7-9cd2-9eaf893aa833.png)

[实例](https://forzeny.github.io/eleApp/dist/#/goods) 

以皮蛋瘦肉粥为例
```less
&.slide-enter-active,
&.slide-leave-active {
	transition: all 0.5s;
}
&.slide-enter,
&.slide-leave-to {
        opacity: 0;
	transform: translate3d(100%, 0, 0);
}
```
enter
```less
0.no class
1.slider-enter 
2.slider-enter && slide-enter-active
3.slider-enter && slide-enter-active && slider-enter-to
4.slide-enter-active && slider-enter-to
5.no class
```
leave
```less
0.no class
1.slider-leave
2.slider-leave && slider-leave-active
3.slider-leave && slide-leave-active && slider-leave-to
4.slide-leave-active && slider-leave-to
5.no class
```
